CREATE TABLE `admin_roles`(
	`role_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '角色号' ,
	`name` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '角色名称' ,
	`remark` TEXT COMMENT '角色备注信息' ,
	`apis` MEDIUMTEXT COMMENT '后端api限制' ,
	`views` MEDIUMTEXT COMMENT '前端页面限制' ,
	`create_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间' ,
	`update_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间' ,
	PRIMARY KEY(`role_id`)
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8 COMMENT = 'admin用户角色表';