CREATE TABLE `admin_user`(
	`user_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'admin用户号' ,
	`role_id` INT(11) COMMENT '角色号',
	`real_name` CHAR(20) NOT NULL DEFAULT '' COMMENT 'admin用户真实名字，可以用来记录日志' ,
	`nick_name` VARCHAR(255) NOT NULL DEFAULT 'admin用户昵称，可以用来显示' ,
	`ip` CHAR(30) NOT NULL DEFAULT '' COMMENT '记录登陆用户ip地址' ,
	`avatar` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '用户头像' ,
	`create_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`update_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
	PRIMARY KEY(`user_id`)
) ENGINE = INNODB AUTO_INCREMENT = 10000 DEFAULT CHARSET = utf8 COMMENT = 'admin用户信息表';